version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '8080:3000'
  api-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [npm, run, test]
