version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3000:3000'
    environment:
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: taskmanagement
      PGPASSWORD: taskmanagement
      PGPORT: 5432
  db:
    image: postgres
    restart: always
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: taskmanagement
      POSTGRES_DB: taskmanagement
