version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3000:3000'
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: task_management
      PGPASSWORD: task-management
      PGPORT: 5432
  api-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [npm, run, test]
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: task_management
      PGPASSWORD: task-management
      PGPORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: task-management
